# Generated by Django 4.0.4 on 2022-05-02 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RecipePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=70)),
                ('short_description', models.CharField(max_length=70)),
                ('cooking_directions', models.TextField(max_length=500)),
                ('cooking_tips', models.TextField(max_length=500)),
                ('cooking_time', models.IntegerField()),
                ('preparation_time', models.IntegerField()),
                ('recipe_images', models.ImageField(upload_to='media/%Y/%m/%d')),
                ('recipe_datePosted', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('Author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ingredients', models.ManyToManyField(to='adminapp.ingredient')),
            ],
        ),
    ]
