# Generated by Django 4.0.4 on 2022-05-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_remove_recipepost_ingredients_delete_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipepost',
            name='ingredients',
            field=models.CharField(default=0, max_length=300),
        ),
    ]
