# Generated by Django 4.0.4 on 2022-05-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_alter_recipepost_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipepost',
            name='cooking_directions',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='recipepost',
            name='ingredients',
            field=models.CharField(default=0, max_length=300),
        ),
    ]
