# Generated by Django 4.0.4 on 2022-05-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_alter_recipepost_cooking_directions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipepost',
            name='ingredients',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
